### ISSUE TITLE
Server.Interop.Callbacks.ActionCallback not called

### ISSUE THREAD

**Issue by bartengine27** [canhorn/EventHorizon.Blazor.Interop.Generator#2]
Dear,

  Thanks for sharing your code, great work! 

  I tried the EventHorizon.Blazor.Server.BabylonJS sample and noticed that after putting a breakpoint on AnimationExample.razor.cs at line 76 the action callback is never called.

  Is this expected behavior?

Thanks,
Bart

**Comment by canhorn** [comment]
Thanks for pointing this out.

The issue is with the version of BabylonJS, it is currently set to always use the current preview of BabylonJS.
I will make a small update so the examples use the version that is used to generate the C#.

Cody

**Comment by bartengine27** [comment]
Hi Cody,

  Solved, thank you!

Regards,
Bart
